knp_paginator:
    page_range: 5                       # nombre de liens affichés dans le menu de pagination
    default_options:
        page_name: page                 # nom du paramètre de requête pour la page
        sort_field_name: sort           # nom du paramètre de requête pour le tri
        sort_direction_name: direction   # nom du paramètre de requête pour la direction du tri
        distinct: true                   # assurer des résultats distincts
        filter_field_name: filterField    # nom du paramètre de requête pour le filtre
        filter_value_name: filterValue    # nom du paramètre de requête pour la valeur du filtre
    template:
        pagination: '@KnpPaginator/Pagination/bootstrap_v5_pagination.html.twig'  # modèle de contrôles de pagination
        sortable: '@KnpPaginator/Pagination/sortable_link.html.twig'              # modèle de lien de tri
        filtration: '@KnpPaginator/Pagination/filtration.html.twig'                # modèle de filtres
